/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ClientRouteImport } from './routes/client'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminStaffLoginRouteImport } from './routes/admin/staff-login'
import { Route as AdminLoginAgentRouteImport } from './routes/admin/login/agent'
import { Route as AdminLoginOfficeManagerRouteImport } from './routes/admin/login/office-manager'
import { Route as AdminLoginSuperAdminRouteImport } from './routes/admin/login/super-admin'
import { Route as AdminLoginTeamLeaderRouteImport } from './routes/admin/login/team-leader'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffLoginRoute = AdminStaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginAgentRoute = AdminLoginAgentRouteImport.update({
  id: '/login/agent',
  path: '/login/agent',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginOfficeManagerRoute = AdminLoginOfficeManagerRouteImport.update({
  id: '/login/office-manager',
  path: '/login/office-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginSuperAdminRoute = AdminLoginSuperAdminRouteImport.update({
  id: '/login/super-admin',
  path: '/login/super-admin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginTeamLeaderRoute = AdminLoginTeamLeaderRouteImport.update({
  id: '/login/team-leader',
  path: '/login/team-leader',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/client': typeof ClientRoute
  '/login': typeof LoginRoute
  '/admin/staff-login': typeof AdminStaffLoginRoute
  '/admin/login/agent': typeof AdminLoginAgentRoute
  '/admin/login/office-manager': typeof AdminLoginOfficeManagerRoute
  '/admin/login/super-admin': typeof AdminLoginSuperAdminRoute
  '/admin/login/team-leader': typeof AdminLoginTeamLeaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/client': typeof ClientRoute
  '/login': typeof LoginRoute
  '/admin/staff-login': typeof AdminStaffLoginRoute
  '/admin/login/agent': typeof AdminLoginAgentRoute
  '/admin/login/office-manager': typeof AdminLoginOfficeManagerRoute
  '/admin/login/super-admin': typeof AdminLoginSuperAdminRoute
  '/admin/login/team-leader': typeof AdminLoginTeamLeaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/client': typeof ClientRoute
  '/login': typeof LoginRoute
  '/admin/staff-login': typeof AdminStaffLoginRoute
  '/admin/login/agent': typeof AdminLoginAgentRoute
  '/admin/login/office-manager': typeof AdminLoginOfficeManagerRoute
  '/admin/login/super-admin': typeof AdminLoginSuperAdminRoute
  '/admin/login/team-leader': typeof AdminLoginTeamLeaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/client'
    | '/login'
    | '/admin/staff-login'
    | '/admin/login/agent'
    | '/admin/login/office-manager'
    | '/admin/login/super-admin'
    | '/admin/login/team-leader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/client'
    | '/login'
    | '/admin/staff-login'
    | '/admin/login/agent'
    | '/admin/login/office-manager'
    | '/admin/login/super-admin'
    | '/admin/login/team-leader'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/client'
    | '/login'
    | '/admin/staff-login'
    | '/admin/login/agent'
    | '/admin/login/office-manager'
    | '/admin/login/super-admin'
    | '/admin/login/team-leader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ClientRoute: typeof ClientRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff-login': {
      id: '/admin/staff-login'
      path: '/staff-login'
      fullPath: '/admin/staff-login'
      preLoaderRoute: typeof AdminStaffLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/agent': {
      id: '/admin/login/agent'
      path: '/login/agent'
      fullPath: '/admin/login/agent'
      preLoaderRoute: typeof AdminLoginAgentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/office-manager': {
      id: '/admin/login/office-manager'
      path: '/login/office-manager'
      fullPath: '/admin/login/office-manager'
      preLoaderRoute: typeof AdminLoginOfficeManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/super-admin': {
      id: '/admin/login/super-admin'
      path: '/login/super-admin'
      fullPath: '/admin/login/super-admin'
      preLoaderRoute: typeof AdminLoginSuperAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login/team-leader': {
      id: '/admin/login/team-leader'
      path: '/login/team-leader'
      fullPath: '/admin/login/team-leader'
      preLoaderRoute: typeof AdminLoginTeamLeaderRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminStaffLoginRoute: typeof AdminStaffLoginRoute
  AdminLoginAgentRoute: typeof AdminLoginAgentRoute
  AdminLoginOfficeManagerRoute: typeof AdminLoginOfficeManagerRoute
  AdminLoginSuperAdminRoute: typeof AdminLoginSuperAdminRoute
  AdminLoginTeamLeaderRoute: typeof AdminLoginTeamLeaderRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStaffLoginRoute: AdminStaffLoginRoute,
  AdminLoginAgentRoute: AdminLoginAgentRoute,
  AdminLoginOfficeManagerRoute: AdminLoginOfficeManagerRoute,
  AdminLoginSuperAdminRoute: AdminLoginSuperAdminRoute,
  AdminLoginTeamLeaderRoute: AdminLoginTeamLeaderRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ClientRoute: ClientRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
